server:
  port: 8080
spring:
  application:
    name: verify-code
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/template/
    check-template-location: true
    servlet:
      content-type: text/html

  datasource:
    druid:
      url: jdbc:mysql://45.62.114.57:3306/test?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234567890
      initial-size: 1
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      async-init: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123